eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhsot:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0